name: Publish FAST.FBasicInterpreter package to NuGet.org

on:
  push:
    branches:
      - main # or your default branch, like 'master'
    paths:
      - '/FAST.FBasic/FAST.FBasicInterpreter/FAST.FBasicInterpreter.csproj'
  workflow_dispatch: # Allows manual trigger from the GitHub UI

env:
  PROJECT_PATH: '/FAST.FBasic/FAST.FBasicInterpreter/FAST.FBasicInterpreter.csproj'
  BUILD_CONFIGURATION: 'Release'
  NUGET_FEED_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Use your target .NET version

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build and pack the project
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --output ./nupkg #COUT: --no-build

    - name: Push the package to NuGet.org (Publish)
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.NUGET_FEED_URL }}
      
