name: Deploy to NuGet

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Triggers on tags like v1.0.0, v2.1.5, etc.
    branches:
      - main # or your default branch, like 'master'
  workflow_dispatch: # Allows manual trigger from the GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Get Package Version
      id: get_version
      run: |
        VERSION="${{github.ref_name}}"
        VERSION_WITHOUT_V="${VERSION#v}"
        echo "PACKAGE_VERSION=$VERSION_WITHOUT_V" >> $GITHUB_ENV
      shell: bash
    - name: Build and Pack
      run: dotnet pack FAST.FBasicInterpreter/FAST.FBasicInterpreter.csproj --configuration Release -p:PackageVersion=1.0.0 --output nupkg
      
    - name: Push package to NuGet
      run: dotnet nuget push "nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
