name: Publish .NET package to NuGet.org

on:
  push:
    branches:
      - main # or your default branch, like 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Use your target .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and pack the project
      run: dotnet pack /FAST.FBasic/FAST.FBasic/FAST.FBasicInterpreter/FAST.FBasicInterpreter.csproj --configuration Release --output ./nupkg --no-build
 
    - name: Push the package to NuGet.org
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
